project_id = "ntrdrgkglyutuzlvnqpf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.trade-commodity]
verify_jwt = true

[functions.get-portfolio]
verify_jwt = true